config-version: 2
name: 'workday_employee_overview'
version: '1.0.0'
dbt-cloud:
    project-id: 70403103996657
require-dbt-version: [">=1.3.0", "<3.0.0"]

profile: 'workday_fivetran_dbt'

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]

models:
  workday_employee_overview:
    +schema: workday
    intermediate:
      +materialized: incremental
      +unique_key: ['worker_id', 'source_relation']
      +on_schema_change: append_new_columns
    staging:
      +materialized: view
      +schema: stg_workday
      base:
        +materialized: view
    marts:
      +materialized: table

vars:
    # Source table references - pointing to Workday.workday_raw
    worker_history: "{{ source('workday','worker_history') }}"
    personal_information_common_data: "{{ source('workday','personal_information_common_data') }}"
    country_personal_information: "{{ source('workday','country_personal_information') }}"
    person_name: "{{ source('workday','person_name') }}"
    personal_information_ethnicity: "{{ source('workday','personal_information_ethnicity') }}"
    military_service: "{{ source('workday','military_service') }}"
    person_contact_email_address: "{{ source('workday','person_contact_email_address') }}"
    worker_position_history: "{{ source('workday','worker_position_history') }}"

    # Schema version flag - set to true for V2 schema (default)
    workday__using_personal_info_v2_schema: true
